version: '3.8'
services:
  auth:
    container_name: auth-service
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '${PORT}:${PORT}'
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - authnet
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12
    expose:
      - '${POSTGRES_PORT}'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - authnet

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - authnet

  redis:
    container_name: cache
    image: 'redis'
    expose:
      - '${REDIS_PORT}'
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    env_file:
      - docker.env
    networks:
      - authnet

networks:
  authnet:
    driver: bridge
