export enum ExceptionType {
  CHAR_ONLY_ERROR = 'CHAR_ONLY_ERROR',
  REQUIRED_ERROR = 'REQUIRED_ERROR',
  INVALID_EMAIL_ERROR = 'INVALID_EMAIL_ERROR',
  INVALID_PHONE_ERROR = 'INVALID_PHONE_ERROR',
  PASSWORD_MIN_CHAR_LENGTH_ERROR = 'PASSWORD_MIN_CHAR_LENGTH_ERROR',
  NEW_PASSWORD_MATCH_CURRENT_PASSWORD_ERROR = 'NEW_PASSWORD_MATCH_CURRENT_PASSWORD_ERROR',
}
