image: node:latest

stages:
  - build
  - test

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

run_test:
  stage: test
  script: npm test